### ISSUE TITLE
Make bullets work on Glass Mod Manager

### ISSUE THREAD

**Issue by qu47** [BlocklandGlass/BlocklandGlass#171] opened 2017-01-12 20:52 UTC
Glass Mod Manager currently has no support for bullets. It's pretty obvious, as you can see in the images.

### Images :100: :fire: :fire: :ok_hand:
![bullet2](https://cloud.githubusercontent.com/assets/25020307/21907792/a8afc5fe-d8d6-11e6-9a80-25a17d3737a5.PNG)
_The description on the website (with bullets)._

![bullets](https://cloud.githubusercontent.com/assets/25020307/21907806/b8aed3e6-d8d6-11e6-9ba2-0309a3da34e4.PNG)
_The description on Mod Manager (no bullets, replaced by -'s)._

**Comment by Jincux** [comment] 2017-01-12 21:49
Duplicate of #144

**Closed by Jincux** 2017-01-12 21:49 UTC
Labels: ., Suggestion
