### ISSUE TITLE
(suggestion) Display if friends have passworded their server.

### ISSUE THREAD

**Issue by qu47** [BlocklandGlass/BlocklandGlass#160] opened 2017-01-12 00:40 UTC
_rlcbm told me to suggest this because he doesn't have a Github account_

When a friend passwords their server, they can have it display to their friends so they know that it has been passworded. The host is the only one who can display their messages to their friends, and of course, there will be a privacy setting for this (but should be off by default.)

**Comment by Jincux** [comment] 2017-01-12 00:52
Duplicate of #140, already resolved

**Closed by Jincux** 2017-01-12 00:52 UTC

**Comment by qu47** [comment] 2017-01-12 00:53
isn't it a suggestion for aesthetics
