### ISSUE TITLE
BBCode parsing fails

### ISSUE THREAD

**Issue by Greek2me** [BlocklandGlass/BlocklandGlass#15] opened 2015-07-27 23:37 UTC
When I use this BBCode, nothing is parsed and the plain BBCode is displayed:

	[center][img]http://greek2me.webs.com/Downloads/Gamemode_Slayer/Images/logoSmall.png[/img][/center]
	[color=maroon][b][size=24pt]Slayer[/size][/b][/color]
	[size=24pt]Advanced Game Mode System[/size]

	[color=maroon][b][size=20pt]Features[/size][/b][/color]
	There's tons of features and I don't have space to actually write about all of them. Just be satisfied knowing that this is the most advanced minigame system in Blockland to-date. If you need help with a specific feature, look at the Help tab in the GUI.

	[color=maroon][b][size=20pt]Credits[/size][/b][/color]
	[b]Support Scripts[/b]
	[list][*]Support_SpecialKills - Space Guy / Greek2me
	[*]Support_LibStr - Clockturn
	[*]Support_Pathing - Port / Greek2me[/list]

	[b]Original Testers[/b]
	[list][*]Boom/Deathwishez
	[*]Brian Smith
	[*]KINEX
	[*]Gizmo
	[*]Racerboy[/list]

	[b]Special Thanks[/b]
	[list][*]Jetz
	[*]Pecon7[/list]

**Comment by Jincux** [comment] 2015-07-28 03:50
I've disabled it until I figure out what I'm going to end up using. Most likely markdown.

**Comment by Jincux** [comment] 2015-07-28 03:51
duplicate of #5

**Closed by Jincux** 2015-07-28 03:51 UTC
Labels: duplicate
